spring:
  application:
    name: sub_tech_challenge_seller_api_fase5
  data:
    mongodb:
      uri: mongodb://posfiap:posfiap2@localhost:27017
      database: vehicle

vehicle:
  url: "http://localhost:8080/api/vehicle"